from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from src.config import Settings
from src.diagnostics import overall_status, run_startup_checks
from src.infrastructure.artifact_store import ArtifactStore
from src.presentation.api_serializers import (
    serialize_health_payload,
    serialize_platform_status,
    serialize_run_list_item,
    serialize_run_workspace,
    serialize_settings,
    serialize_transcription_capability,
    serialize_template_catalog,
)
from src.services.summary_service import SummaryService
from src.share_link_ingest import inspect_managed_auth_profile
from src.transcription_runtime import probe_transcription_capability


TOOL_PROGRESS_LIBRARY = {
    "share_link": {
        "title": "当前进度",
        "phaseLabel": "等待输入分享链接",
        "subtitle": "输入有效链接后即可开始执行。",
        "progressPercent": 0,
        "detailLines": ["授权入口已就位，输入有效链接后即可创建新项目任务。"],
        "history": [],
    },
    "local_media": {
        "title": "当前进度",
        "phaseLabel": "等待选择本地媒体文件",
        "subtitle": "选择音视频文件后即可开始执行。",
        "progressPercent": 0,
        "detailLines": ["先选择音视频文件，处理成功后会自动切换到项目工作区。"],
        "history": [],
    },
    "text_input": {
        "title": "当前进度",
        "phaseLabel": "等待输入文本内容",
        "subtitle": "上传文本文件或直接粘贴内容后即可开始执行。",
        "progressPercent": 0,
        "detailLines": ["可上传文本文件或直接粘贴内容，随后进入结构化整理流程。"],
        "history": [],
    },
    "recovery": {
        "title": "当前进度",
        "phaseLabel": "等待恢复来源",
        "subtitle": "选择已有项目或上传恢复目录后即可继续处理。",
        "progressPercent": 0,
        "detailLines": ["打开已有项目，或上传恢复目录继续处理。"],
        "history": [],
    },
}


def export_workspace_runtime_snapshot(
    artifact_store: ArtifactStore,
    settings: Settings,
    output_path: Path,
) -> dict[str, Any]:
    snapshot = build_workspace_runtime_snapshot(artifact_store, settings)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "// This file is generated by Synpture runtime snapshot export.\n"
        f"export const runtimeSnapshot = {json.dumps(snapshot, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    return snapshot


def build_workspace_runtime_snapshot(artifact_store: ArtifactStore, settings: Settings) -> dict[str, Any]:
    summary_service = SummaryService()
    run_items = artifact_store.list_runs()
    templates = summary_service.list_runtime_templates()
    result_payloads: dict[str, Any] = {}
    for item in run_items:
        artifacts = artifact_store.load_run(item.run_dir, settings)
        result_payloads[item.run_dir.name] = serialize_run_workspace(
            item,
            artifacts,
            templates=serialize_template_catalog(templates, artifacts=artifacts),
        )

    health_items = run_startup_checks(settings)
    health_payload = serialize_health_payload(
        health_items,
        has_run=True,
        status=overall_status(health_items),
    )

    return {
        "historyRuns": [serialize_run_list_item(item) for item in run_items],
        "resultPayloads": result_payloads,
        "settingsFormState": serialize_settings(settings),
        "transcription": serialize_transcription_capability(probe_transcription_capability(settings)),
        "healthCheckState": health_payload,
        "toolProgressLibrary": TOOL_PROGRESS_LIBRARY,
        "shareAuthCards": _build_share_auth_cards(),
    }


def _build_share_auth_cards() -> list[dict[str, Any]]:
    cards = [
        _build_platform_card("douyin", "抖音"),
        _build_platform_card("bilibili", "B站"),
        serialize_platform_status(platform="xiaohongshu", title="小红书", inspect_result=None, placeholder=True),
        serialize_platform_status(platform="wechat_butterfly", title="微信蝴蝶号", inspect_result=None, placeholder=True),
    ]
    return cards


def _build_platform_card(platform_key: str, label: str) -> dict[str, Any]:
    try:
        result = inspect_managed_auth_profile(platform_key)
        inspect_result = {
            "ok": result.ok and result.is_logged_in,
            "summary": result.message,
            "details": list(result.details),
        }
    except Exception as exc:
        inspect_result = {"ok": False, "summary": str(exc), "details": [str(exc)]}
    return serialize_platform_status(platform=platform_key, title=label, inspect_result=inspect_result)
